### ISSUE TITLE
Specify request and response documents using json-schema

### ISSUE THREAD

**Issue by mark-burnett** [genome/ptero-apis#16]
[json-schema](http://json-schema.org/documentation.html) seems like it might be a good fit and ease validation.

There is a [python implementation](https://python-jsonschema.readthedocs.org/en/latest/).

**Comment by mark-burnett** [comment]
This is almost done.  The only remaining service not using jsonschema for their primary POST is workflow, and that is in progress: genome/ptero-workflow#65

**Comment by mkiwala** [comment]
genome/ptero-workflow#65 is closed.  Closing this issue.
